name: ai_chat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_ai: ^3.9.0
  firebase_core: ^4.5.0
  equatable: ^2.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  file_picker: ^10.3.10

  get_it: ^8.0.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.11
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0

  objectbox_generator: ^5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_gen:
  output: lib/generated/assets
  line_length: 80
  assets:
    enabled: true
  colors:
    inputs:
      - assets/colors.xml
  
flutter_intl:
  enabled: true

objectbox:
  output_dir: generated/objectbox
  
